### ISSUE TITLE
review comments from using DOCKER_INSTALL.md

### ISSUE THREAD

**Issue by PeterRounce** [onesandzeros-nz/boltcard#2]
reference: [DOCKER_INSTALL.md](https://github.com/onesandzeros-nz/boltcard/blob/7d76797154ca67d4c6a350295ab68771ca581c4a/docs/DOCKER_INSTALL.md)

[1] "docker compose" step not needed - it's included with the "docker" step

[2] "chmod +x" step not needed

[3] nice reminder step re. opening firewall for 443 - thanks

[4] error on this step  

$ docker volume create caddy_data

```
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/volumes/create": dial unix /var/run/docker.sock: connect: permission denied
```

was fixed with  

$ sudo groupadd docker
$ sudo usermod -aG docker ${USER}
(log out & in again)
$ docker volume create caddy_data

caddy_data

[5] compose command

$ docker-compose up -d

should be

$ docker compose up -d

[6] put allow_neg_bal in the example so the card works, i.e.

$ docker exec boltcard_main createboltcard/createboltcard -enable -tx_max=1000 -day_max=10000 -name=card_1

may be better as

$ docker exec boltcard_main createboltcard/createboltcard -enable -allow_neg_bal -tx_max=1000 -day_max=10000 -name=card_1

[7] how to access log?

card was written ok including ‘bolt call test’

POS payment failed

how do I access the service log on the docker container to debug?

( $ journalctl -u boltcard.service -f ) or similar

**Comment by chloehjung15** [comment]
1-6 ) will update
7 ) if you run `$ docker logs ${container_id | container_name} `
You can see all the logs for that container. Call `$ docker ps ` to get all running containers id and name. 
If you add --follow flag to the docker log command you'll be able to live tail the logs. 
Also if you don't add the -d flag when you're running `docker compose run` command, you'll be able to see all the logs for all containers.

**Comment by PeterRounce** [comment]
https://github.com/onesandzeros-nz/boltcard/blob/main/docker_init.sh

```
sed -i "s/[(]'LN_TLS_FILE'[^)]*[)]/(\'LN_TLS_FILE\', \'\/boltcard\/cert.tls\')/" settings.sql
```

`cert.tls` should be `tls.cert`

**Comment by chloehjung15** [comment]
Oops sorry not sure why I wrote that the other way around haha. 
All updated. Glad to hear it's all working on your end as well!
